    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AZURE_HOST }}
        username: ${{ secrets.AZURE_USER }}
        password: ${{ secrets.AZURE_PASSWORD }}
        script: |
          cd /home/${{ secrets.AZURE_USER }}

          # Clone repo if missing
          if [ ! -d "myapp" ]; then
            git clone https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }} myapp
          fi

          # Update repo
          cd myapp
          git fetch --all
          git reset --hard origin/main

          # Backend setup
          cd backend
          npm install

          # Frontend build
          cd ../frontend
          npm install
          npm run build

          # Deploy build to Nginx
          sudo rm -rf /var/www/myapp/*
          sudo cp -r dist/* /var/www/myapp/

          # Restart backend with PM2
          cd ../backend
          pm2 restart myapp-backend || pm2 start npm --name myapp-backend -- start
          pm2 save
